<?php
namespace tree\core;

/**
 * No direct access to this file.
 */
if (!defined('ABSPATH')) {
    exit;
}


/**
 * Class      DatabaseModel abstract class
 * @category  Core Components
 * @author    Ferencz Andras <contact@ferenczandras.ro>
 * @copyright Copyright (c) 2016-2017 Affarit Studio
 * @license   http://opensource.org/licenses/gpl-3.0.html GNU Public License
 * @link      https://github.com/ferenczAndras/tree
 * @link      http://www.affarit.com
 */
abstract class DatabaseModel extends Object
{

    /**
     * @var array mixed holds the messages generated by the model
     */
    protected $messages = array();

    /**
     * @var string $table holds the table name for this object
     */
    protected $table;


    /**
     * @param $message String the message we want to hold
     */
    public function addMessage($message)
    {
        $this->messages[] = $message;
    }

    /**
     * @return array which holds all the messages
     */
    public function getMessages()
    {
        return $this->messages;
    }

    /**
     * Returns the current table value
     * @return string
     */
    public function getTable()
    {
        if (empty($this->table))
            throw new EmptyVariableException("Table not defined.");

        return $this->table;
    }

    /**
     * @param $table string sets the table value
     */
    public function setTableName($table)
    {
        $this->table = $table;
    }

    /**
     * @param $key
     * @param null $defaultValue
     */
    public function get($key, $defaultValue = null)
    {
        throw new UnImplementedMethodException('Calling un implemented method: ' . get_class($this) . "::get()");
    }

    /**
     * @param $key
     * @param $value
     */
    public function insert($key, $value)
    {
        throw new UnImplementedMethodException('Calling un implemented method: ' . get_class($this) . "::insert()");
    }

    public function reset()
    {
        throw new UnImplementedMethodException('Calling un implemented method: ' . get_class($this) . "::reset()");
    }

    public function drop()
    {
        throw new UnImplementedMethodException('Calling un implemented method: ' . get_class($this) . "::drop()");
    }

    public function install()
    {
        throw new UnImplementedMethodException('Calling un implemented method: ' . get_class($this) . "::install()");
    }

}